name: evogil

dependencies:
    - python=3.6
    - numpy==1.14.2
    - docopt=0.6.2
    - matplotlib=2.2.2
    - scipy=1.0.1
    - pip:
      - git+git://github.com/ReactiveX/RxPY.git@master#egg=rx
      - floatextras==0.0.3
